# Generated by Django 4.2.4 on 2023-08-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField()),
                ('sightseeing', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('food_and_drinks', models.TextField(blank=True, null=True)),
                ('transport', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
