# Generated by Django 4.2.4 on 2023-08-09 20:17

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='transport',
        ),
        migrations.AddField(
            model_name='trips',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
