# Generated by Django 4.2.4 on 2023-08-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trips_notes_remove_trips_transport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='type',
            field=models.CharField(default=212, max_length=6, verbose_name='Trip type'),
            preserve_default=False,
        ),
    ]
