# Generated by Django 4.2.4 on 2023-08-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trips_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='transport',
            field=models.TextField(blank=True, null=True),
        ),
    ]
