# Generated by Django 4.2.4 on 2023-08-10 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trips_publication_date_trips_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='trip_name',
            field=models.CharField(default=123123, max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
    ]
