# Generated by Django 4.2.4 on 2023-08-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_trips_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='agency',
        ),
        migrations.AddField(
            model_name='trips',
            name='used_agency',
            field=models.CharField(choices=[('Shanotur', 'Shanotur'), ('WWWd', 'WWWd')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
