# Generated by Django 4.2.4 on 2023-08-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_remove_trips_agency_trips_used_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='used_agency',
            field=models.CharField(choices=[(1, 'Shanotur'), (2, 'Denita')], max_length=30),
        ),
    ]
