# Generated by Django 4.2.4 on 2023-08-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_trips_used_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='used_agency',
            field=models.CharField(choices=[('Shanotur', 1), ('Denita', 2)], max_length=30),
        ),
    ]
