# Generated by Django 4.2.4 on 2023-08-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_trips_used_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
