# Generated by Django 4.2.4 on 2023-08-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_trips_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='used_agency',
            field=models.CharField(blank=True, choices=[('Shanotur', 'Shanotur'), ('Denita', 'Denita'), ('Other (add in notes)', 'Other (add in notes)')], max_length=30, null=True),
        ),
    ]
