# Generated by Django 4.2.4 on 2024-01-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_alter_trips_used_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trips_photos')),
                ('trip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trips.trips')),
            ],
        ),
    ]
