# Generated by Django 4.2.4 on 2024-01-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='trip',
        ),
        migrations.AddField(
            model_name='trips',
            name='photos',
            field=models.ManyToManyField(blank=True, to='trips.photos'),
        ),
    ]
