# Generated by Django 4.2.4 on 2024-02-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_remove_photos_trip_trips_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=2000),
            preserve_default=False,
        ),
    ]
