# Generated by Django 4.2.4 on 2024-02-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_photos_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='trips_photos'),
        ),
    ]
