# Generated by Django 4.2.4 on 2024-02-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('trips', '0020_alter_photos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='used_agency',
            field=models.ForeignKey(choices=[('Denita', 'Denita'), ('Other (add in notes)', 'Other (add in notes)'), ('None', 'None'), ('Shanotur', 'Shanotur')], default=1, max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='agencies.agencies'),
            preserve_default=False,
        ),
    ]
