# Generated by Django 4.2.4 on 2024-02-22 19:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('trips', '0021_alter_trips_used_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='used_agency',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='agencies.agencies'),
        ),
    ]
