# Generated by Django 4.2.4 on 2023-08-11 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('agency_website', models.URLField()),
            ],
        ),
    ]
