# Generated by Django 4.2.4 on 2023-08-11 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_alter_trips_used_agency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoComment',
            new_name='TripComment',
        ),
    ]
