# Generated by Django 4.2.4 on 2023-08-12 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_alter_trips_used_agency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_rename_photocomment_tripcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('trip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='trips.trips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
