# Generated by Django 4.2.4 on 2023-08-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_triprating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprating',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
