# Generated by Django 4.2.4 on 2023-08-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_trips_average_rating'),
        ('common', '0007_alter_tripcomment_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprating',
            name='trip',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trips.trips'),
        ),
    ]
